@extends('layouts.app')

@section('title', 'Blog')

@section('logout')
    <form action="{{ route('logout') }}" method="POST">
        @csrf
        <button type="submit"
            class="font-semibold text-lg border border-white rounded-md px-2 hover:bg-white hover:text-slate-800">Logout</button>
    </form>
@endsection

@section('sub-title')
    <h2 class="test w-4/5 mx-auto my-3 text-left text-lg font-medium ">
        We love A.I. and welcome you to our AI blog. There is so much going on in the field of AI and our goal is to keep
        you up-to-date in innovative, informative, and entertaining ways. We see this website as a form of digital art as
        all images and text were generated by artificial intelligence (with a little bit of human help). This AI blog is
        written and designed by impressive AIs, and humans merely perform copy & paste operations - we showcase the progress
        of AI capabilities on all fronts (text, image, video, audio, design, technology, education, etc). </h2>
@endsection

@section('hero-image')
    <div class="hero-image w-full my-10">
        <img src="/images/hero-image.jpg" alt="" class="mx-auto">
    </div>
@endsection

@section('main-title')
    <h1 class="main-title text-5xl border-b border-sky-700 max-w-max mx-auto pb-4 mb-8">AI Blog & AI News
    </h1>
@endsection

@section('content')
    {{-- Add-post-button --}}
    <a href="{{ route('post.create') }}"
        class="bg-sky-700 px-4 py-2 text-white rounded-lg border border-transparent hover:border-slate-50">Add New Post
        +</a>
    {{-- posts --}}
    <div class="posts flex gap-x-8 gap-y-9 my-12 flex-wrap justify-start">
        @forelse ($posts as $post)
            <div class="card max-w-64 rounded-xl text-white  bg-gray-700 h-full">
                {{-- post-image --}}
                <img src="./images/{{ $post->image }}" alt="" class=" rounded-tr-xl  rounded-tl-xl">
                {{-- post-content --}}
                <div class="content py-3 px-2">
                    <p class="text-sm -mb-1 font-semibold">{{ $post->category->title }}</p>
                    <a href="{{ route('post.show', $post->id) }}" class="hover:underline">
                        <h2 class="post-title text-xl">{{ $post->title }}</h2>
                    </a>
                    <p class="desc my-2 text-sm">{{ $post->description }}</p>
                    {{-- post-actions (update or delete) --}}
                    <div class="actions flex justify-center gap-6 py-4">
                        @if (auth()->check() && auth()->user()->can('update', $post))
                            <a href="{{ route('post.edit', $post->id) }}"
                                class="bg-sky-600 px-6 py-2 rounded-sm border border-transparent hover:border-slate-50">Edit
                                <i class="fa-solid fa-pen-to-square"></i></a>
                        @endif
                        @if (auth()->check() && auth()->user()->can('delete', $post))
                            <form action="{{ route('post.destroy', $post->id) }}" method="POST"
                                class="bg-red-700 px-4 py-2 rounded-sm cursor-pointer border border-transparent hover:border-slate-50">
                                @csrf
                                @method('DELETE')
                                <input type="submit" value="Delete" class="cursor-pointer">
                                <i class="fa-solid fa-trash"></i>
                            </form>
                        @endif
                    </div>
                </div>
            </div>
            {{-- message if no posts --}}
        @empty
            <p class="text-white text-xl">No Posts</p>
        @endforelse
    </div>
@endsection
